<?php

namespace Samsin33\Razorpay\Models;

use Illuminate\Database\Eloquent\Relations\BelongsTo;
use Illuminate\Database\Eloquent\Model;
use Samsin33\Razorpay\Services\PaymentApi;

class RzpOrderPayment extends Model
{
    protected $fillable = ['order_id', 'rzp_payment_id', 'rzp_signature', 'status', 'data', 'ipaddress'];
    protected $visible = ['id', 'order_id', 'rzp_payment_id', 'rzp_signature', 'status', 'data', 'ipaddress',
        'created_at', 'updated_at'];

    protected static function booted()
    {
        parent::booted(); // TODO: Change the autogenerated stub
        static::creating(function ($rzp_order_payment) {
            $rzp_order_payment->ipaddress = request()->ip();
        });
    }

    //--------------------- Relationships ------------------------------
    public function order(): BelongsTo
    {
        return $this->belongsTo(config('razorpay.order_model'), 'order_id', 'id');
    }

    //--------------------- Other Functions ----------------------------
    public function verifyWebhook()
    {
        $payment = new PaymentApi();
        return $payment->verifyWebhookSignature($this->data, $this->rzp_signature);
    }
}